
public class exception {
	
	static void check()
	{
		int a=4,b=0;
		try
		{
			int c = a/b;
			System.out.println("denominator is zero");
		}
		catch(ArithmeticException ae){
			//System.out.println("exception is"+ae);
			ae.printStackTrace();
		}
		
	}
	
	public static void main(String[] args) {
		check();
		
	}

}
